# Generated by Django 5.2 on 2025-12-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillvideo',
            name='youtube_url',
            field=models.CharField(default=1, help_text='Extracted YouTube Video ID (e.g., dQw4w9WgXcQ)', max_length=50),
            preserve_default=False,
        ),
    ]
