# Generated by Django 4.2.7 on 2025-11-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_feature',
            field=models.BooleanField(default=False, help_text='Mark product as featured for top picks'),
        ),
    ]
